---
- name: Install tomcat
  package:
    name: tomcat
    update_cache: yes
    state: latest

- name: ensure tomcat is running
  service:
    name: tomcat
    state: started

- name:
  package:
    name: tomcat-webapps
    state: latest

- name:
  package:
    name: tomcat-admin-webapps
    state: latest


    


